
main.pdf:
	agda --latex PeterCastCalculus.lagda
	agda --latex PeterFestschrift.lagda
	agda --latex PeterFundamental.lagda
	agda --latex PeterGG.lagda
	cd latex/LogRel; /Library/TeX/texbin/pdflatex main
	cd latex/LogRel; /Library/TeX/texbin/pdflatex main
